version: '4.0'

services:
  postgres:
    image: postgres:16.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  home_controller:
    image: home_controller:latest
    ports:
      - "8080:8080"
      - "80:80"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/db # postgres postgres postgres postgres postgres postgres postgres postgres
      - HTTP_PORT=80
      - HTTP_HOST=0.0.0.0
      - METRICS_PORT=8080
